### ISSUE TITLE
Configurability in log levels sent to sentry 

### ISSUE THREAD

**Issue by Sricharan-H** [TeoZosa/structlog-sentry-logger#1114]
Is there a way to allow the user of the library to configure the log level in `SentryBreadcrumbJsonProcessor`? 

I have a use case where I want to send warnings as events in sentry if they occur more than a particular frequency of time. However, I am unable to modify the log level of the `SentryBreadcrumbJsonProcessor` as it is hard coded to `logging.ERROR` as shown [here](https://github.com/TeoZosa/structlog-sentry-logger/blob/0d2005ad25905f9ad783c7bc2bf2ca5c862e3787/structlog_sentry_logger/_config.py#L336). 

Two questions: 
1. Am I missing something obvious to control the levels at which I can log into sentry?
2. Is there any reason as to why we do not have a way to configure log levels for pushing events to sentry?  ( This is moot if the answer of 1) is a "Yes")

**Comment by TeoZosa** [comment]
Hi @Sricharan-H thanks for raising the issue. I only just now saw this. Your use-case makes sense and is something I can make configurable in an upcoming release. 

> Is there any reason as to why we do not have a way to configure log levels for pushing events to sentry?

When this library was originally written, I made the design choice to minimize configuration outside of the bare essentials to, as much as possible, reduce onboarding complexity. But at the same time keeping the door open to extension for configurations that are actually appreciably useful to users.
