### ISSUE TITLE
Is GIT actually needed ?

### ISSUE THREAD

**Issue by mariusmitrofan** [TeoZosa/structlog-sentry-logger#363]
Hi,

When running this in AWS Lambda, I get the following error (truncated):
```
FaultException('Runtime.ImportModuleError', "Unable to import module 'index': Failed to initialize: Bad git executable.\nThe git executable must be specified in one of the following ways:\n    - be included in your $PATH\n    - be set via $GIT_PYTHON_GIT_EXECUTABLE\n    - explicitly set via git.refresh()\n\nAll git commands will error until this is rectified.\n\nThis initial warning can be silenced or aggravated in the future by setting the\n$GIT_PYTHON_REFRESH environment variable. Use one of the follow...
```

A temporary solution for me is to include a GIT layer (https://github.com/lambci/git-lambda-layer), but this workaround might (and I'm pretty sure *will*) cause a pain of errors for me in the future.

Is there a possibility to drop this library from being used ?

The only file that uses this is `_config.py` and it's simply to get the "root dir".

Can we maybe get the root dir in some other way and remove the gitpython dependency ?

Other than that, your project is amazing. If I could, I would buy you a beer @TeoZosa .

Thanks :)

**Comment by mariusmitrofan** [comment]
Also, looks like the root dir in Lambda that is used by your code is `/var/task`.

So when creating `/var/task/.logs`, I get the error:

```
[Errno 30] Read-only file system: '/var/task/.logs'
```

AWS Lambda does not support writing "randomly" in containers, instead it only allows the read-write use of `/tmp` folder with a max size of 512 MB.

Can we maybe set up an environment variable that we can use to bypass the "root dir" detection and explicitly force the library to use a different root dir maybe @TeoZosa ?

**Comment by mariusmitrofan** [comment]
Created PR https://github.com/TeoZosa/structlog-sentry-logger/pull/364/files

@TeoZosa  > Please review and let me know if my solution proposal works "globally" or it's something that I should just fork and continue by myself.

Thanks :)

**Comment by TeoZosa** [comment]
Hey @mariusmitrofan I'm glad you're finding the library useful and thanks for the issue! I definitely think those are valid points and I don't see why we couldn't integrate those features.

I'd love to look at #364 this week and get back to you. Does that work?

**Comment by mariusmitrofan** [comment]
@TeoZosa 

Because of the internal urgency of the matter I created a different repo and launched it as a different library here - https://github.com/Rungutan/structlog-sentry-lambda

I preserved all references to your work and gave you credit for it, but because I especially configured it to work with AWS services I made a few extra tweaks.

I hope that's ok with you.

**Comment by TeoZosa** [comment]
@mariusmitrofan works for me and I appreciate the acknowledgment! Good luck, I'm looking forward to seeing the cool new features you come up with in your version :)
